### PR TITLE
Added sparse grid functionality to SC model

### PR DESCRIPTION
**Pull request by wedeling**
I did some work on the SC analysis and sampling classes. Sparse grids did not work well before, now we can do sparse grid interpolation, quadrature and compute (all) Sobol indices on a sparse grid. The only modified files are:

`easyvvuq/sampling/stochastic_collocation.py`
`easyvvuq/analysis/sc_analysis.py`

And I've also added a sparse grid test for an advection diffusion toy problem in

`tests/sc/sparse_sc_test.py`

From here on, we could also add (dimension) adaptive sampling capability

### CODE REVIEW

**Comment by raar1** [comment]
Hi @wedeling , I was able to get this to work with chaospy version 3.0.4 (which I assume is the one you have) but for v3.0.7 upwards I get the following error:
```
TypeError: generate_quadrature() got an unexpected keyword argument 'normalize'
```
from ```easyvvuq/sampling/stochastic_collocation.py:``` when running the test.

Do you know if there's a quick fix for this?

**Comment by raar1** [comment]
@wedeling hmmm, so I think they've just removed the ```normalize``` keyword completely (there appears not to be any replacement). I tried just removing ```normalize=True``` from the ```generate_quadrature()``` calls in your SC sampler, and the test still gives the same results. This makes me think it is normalizing by default?

**Comment by wedeling** [comment]
Hi @raar1 I used 3.0.5. If the test results remain the same, it's probably doing the normalization by default yes. I'll update my chaospy and do some tests

**Comment by raar1** [comment]
Thanks! Yes, there were a few keyword changes in CP recently, but I think we've dealt with most of them now. As long as this version (without normalize=True) is still ok then I can merge it and put it in the new release this afternoon.

**Comment by raar1** [comment]
I'm fixing the month 15 release (v0.4) at CP v3.0.7, so things should be stable for a bit after that.

**Comment by wedeling** [comment]
I did some tests with 3.0.7 without the normalize statement, and at a first glance things seems to work the same indeed

**Comment by raar1** [comment]
Cool. Hopefully that's all it is.
